name: EasyGameMode
main: uk.co.speshkittyonline.gameMode.EasyGameMode
version: 2
author: Sir_Speshkitty
description: A simpler way to handle /gamemode
commands:
    gamemode:
        description: Changes a players gamemode
        usage: |
            /gamemode [player] [0||1]
permissions:
  gamemode.self:
    default: op
    description: Allows you to change your own gamemode.
  gamemode.other:
    default: op
    description: Allows you to change other people's gamemode.